#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiroaki Ohmatsu
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

name = ["天才肌", "リーダー気質", "努力家", "チャレンジ精神豊富", "人気者" ] 

try:
    number = input("1~5のうち好きな数字を打ち込んでください: ")
    number = int(number)
    if number < 1 or number > 5:
        print("1から5のうちにしてください")
        sys.exit(1)
except ValueError:
    print("数字にしてください")
    sys.exit(1)


if number == 1:
    print("1を選んだあなたは、{}!".format(random.choice(name)))
    
elif number == 2:
    print("2を選んだあなたは、{}!".format(random.choice(name)))

elif number == 3:
    print("3を選んだあなたは、{}!".format(random.choice(name)))

elif number == 4:
    print("4を選んだあなたは、{}!".format(random.choice(name)))

elif number == 5:
    print("5を選んだあなたは、{}!".format(random.choice(name)))








