#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiroaki Ohmatsu
# SPDX-License-Identifier: BSD-3-Clause

import sys


x = [float(n) for n in sys.stdin.read().split()]


x.sort()

n = len(x)

if n == 1:
    median = x[0]

elif n % 2 == 1:
    median = x[n // 2]
else:
    median = (x[n // 2 - 1] + x[n // 2]) / 2

print(median)









